### ISSUE TITLE
Create main activities we will need

### ISSUE THREAD

**Issue by jmezna** [IoSL-INav/android#3]
Login screen, menu screen (share, find),  find screen (which will later show map), share screen, maybe pin position screen?

**Comment by numbleroot** [comment]
My additions:
- menu screen: share, find, friends, settings (small icon top right, maybe)
- friends screen: list of friends with small "X" next to them in order to unfriend, small icon top right to add new friend via TU mail
- settings screen: logout, delete account, future: bluetooth timing
- find screen: we need to discuss how a "navigation towards friends" should be visualized
